# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 283ebfdcbf0febd40e06071f0f6832a942c18e2f29936e4bbb589e2f5760bfe5ccc47c774e5cd46ba294733a68ae388193346ec1a24ecbbe84e6a6f251dfba97

test:
  secret_key_base: 7e8964024f792230b2645aeb5c37e45f27e8dc28e0ae965fa6e82aa97ac6f11c8d355b184d095afdc07027d6c67c32ec5c8f031f50cca88189b65e824b735bc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
